before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - 'echo -e "Host gc-aegir\n	HostName 54.66.226.9\n	User aegir" >> ~/.ssh/config'

phpunit:
  tags: ["php7", "phpunit", "composer"]
  cache: { paths: ["vendor/"] }
  script: composer install --no-dev && phpunit
